[font]
size = 12.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"



[cursor.style]
shape = "Beam"
blinking = "On"



[window]
opacity = 1
padding = { x = 7, y = 7 }
[colors.bright]
black = "#444444"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#fbf1c7"
text = "#3c3836"

[colors.dim]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#a89984"
yellow = "#b57614"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.selection]
background = "#3c3836"
text = "#fbf1c7"
